"""added the survay state in the table

Revision ID: 111393ddcc31
Revises: c26d2e3972d4
Create Date: 2026-04-22 18:07:30.574235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111393ddcc31'
down_revision: Union[str, Sequence[str], None] = 'c26d2e3972d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('state', sa.Enum('draft', 'active', 'close', name='state'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'state')
    # ### end Alembic commands ###
