"""added the survay state in the table

Revision ID: 47a47a0a097c
Revises: ca7b331bbfb2
Create Date: 2026-04-23 04:35:27.582043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a47a0a097c'
down_revision: Union[str, Sequence[str], None] = 'ca7b331bbfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    "ALTER TABLE tokens ALTER COLUMN owner_id TYPE UUID USING owner_id::uuid"
    )
    op.create_foreign_key(None, 'tokens', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.alter_column('tokens', 'owner_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
