"""added the survay state in the table

Revision ID: 9cf945c34cf3
Revises: 47a47a0a097c
Create Date: 2026-04-23 04:46:00.357205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf945c34cf3'
down_revision: Union[str, Sequence[str], None] = '47a47a0a097c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_foreign_key(None, 'tokens', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.alter_column('tokens', 'owner_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
