"""added the survay state in the table

Revision ID: b4d0ebac96f6
Revises: c90a4c5c6935
Create Date: 2026-04-22 18:18:27.501127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d0ebac96f6'
down_revision: Union[str, Sequence[str], None] = 'c90a4c5c6935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('state', sa.Enum('draft', 'active', 'close', name='states'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'state')
    # ### end Alembic commands ###
