"""updated the survay enum's

Revision ID: ba602775c6a7
Revises: 8463d2fb39cf
Create Date: 2026-04-14 06:34:28.383036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba602775c6a7'
down_revision: Union[str, Sequence[str], None] = '8463d2fb39cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new enums with lowercase values
    agegroup_enum = postgresql.ENUM('child', 'teen', 'adult', 'senior', name='agegroup_new', create_type=True)
    gender_enum = postgresql.ENUM('male', 'female', name='gender_new', create_type=True)
    agegroup_enum.create(op.get_bind())
    gender_enum.create(op.get_bind())

    # Alter columns using USING clause to cast old uppercase values to new lowercase
    op.execute("ALTER TABLE surveys ALTER COLUMN age_group TYPE agegroup_new USING lower(age_group::text)::agegroup_new")
    op.execute("ALTER TABLE surveys ALTER COLUMN gender TYPE gender_new USING lower(gender::text)::gender_new")

    # Drop old enums
    op.execute("DROP TYPE agegroup")
    op.execute("DROP TYPE gender")

    # Rename new enums to original names
    op.execute("ALTER TYPE agegroup_new RENAME TO agegroup")
    op.execute("ALTER TYPE gender_new RENAME TO gender")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'gender',
               existing_type=sa.Enum('male', 'female', name='genders'),
               type_=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               existing_nullable=True)
    op.alter_column('surveys', 'age_group',
               existing_type=sa.Enum('child', 'teen', 'adult', 'senior', name='agegroups'),
               type_=postgresql.ENUM('CHILD', 'TEEN', 'ADULT', 'SENIOR', name='agegroup'),
               existing_nullable=True)
    # ### end Alembic commands ###
