"""sd

Revision ID: c26d2e3972d4
Revises: 82a542d19ccb
Create Date: 2026-04-22 17:32:52.065052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26d2e3972d4'
down_revision: Union[str, Sequence[str], None] = '82a542d19ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Enum('child', 'teen', 'adult', 'senior', name='agegroups'), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='genders'), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.add_column('surveys', sa.Column('question', sa.JSON(), nullable=False))
    op.drop_column('surveys', 'gender')
    op.drop_column('surveys', 'age_group')
    op.drop_column('surveys', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('surveys', sa.Column('age_group', postgresql.ENUM('child', 'teen', 'adult', 'senior', name='agegroup'), autoincrement=False, nullable=True))
    op.add_column('surveys', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender'), autoincrement=False, nullable=True))
    op.drop_column('surveys', 'question')
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    # ### end Alembic commands ###
