"""added the survay state in the table

Revision ID: c90a4c5c6935
Revises: b90fd568e000
Create Date: 2026-04-22 18:12:45.990985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90a4c5c6935'
down_revision: Union[str, Sequence[str], None] = 'b90fd568e000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ Step 1: create enum type
    state_enum = sa.Enum('draft', 'active', 'close', name='states')
    state_enum.create(op.get_bind())

    # ✅ Step 2: add column using that enum
    op.add_column(
        'surveys',
        sa.Column('state', state_enum, nullable=False)
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('surveys', 'state')

    state_enum = sa.Enum('draft', 'active', 'close', name='states')
    state_enum.drop(op.get_bind())# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'state')
    # ### end Alembic commands ###
