"""added the title on survey

Revision ID: d2a8276228d1
Revises: 94e57e11ce4b
Create Date: 2026-04-23 08:38:21.157748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a8276228d1'
down_revision: Union[str, Sequence[str], None] = '94e57e11ce4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'title')
    # ### end Alembic commands ###
